#157731613 Add-fitbit-support
andela/wg-rogue-one pull request #16
Opened 2018-06-12 17:31 UTC by peterwade153

### What does this PR do?
Add Fitbit support
#### Description of Task to be completed?
This will allow user get weight and exercise information from Fitbit API.
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#157731613

2018-06-14 09:01 UTC, emugaya commented on wger/core/views/fitbit.py
> +    REDIRECT_URI = 'http://127.0.0.1:8000/en/dashboard'
These should be in the general settings file and in an environment variable.

2018-06-16 20:14 UTC, emugaya requested changes
Fix merge conflicts.
Stop hardcoding` urls` in your work. use environement variables and use enviroment variables to store tokens and other information

2018-06-17 18:47 UTC, hariclerry commented
Code Looks great so far.

2018-06-18 07:08 UTC, emugaya commented on wger/core/views/fitbit.py
> +    #APP SETTINGS FOR FITBIT
Move these settings in the `settings file`

2018-06-18 07:08 UTC, emugaya commented on wger/core/views/fitbit.py
> +            'Authorization' : 'Basic MjJEMjRZOmVkNjQ5OTA2N2M4MDQ5NTgyMWU1YTQxYzliODFlNWNl',
Remove this token. Don't hardcode tokens...

2018-06-20 18:55 UTC, hariclerry requested changes

2018-06-20 18:55 UTC, hariclerry commented on wger/weight/views.py
> +            print(weight_data)
Please remember to remove this line when you are done.

2018-06-20 18:55 UTC, hariclerry commented on wger/weight/static/js/weight.js
> +      console.log(json)
Please remember to remove this line when you are done.

2018-06-21 19:29 UTC, dondrzzy reviewed
@peterwade153  Looks good

2018-06-25 10:54 UTC, merged