feat(make-translation-easier) Make translations of exercises and ingr…
andela/wg-rogue-one pull request #26
Opened 2018-06-22 07:19 UTC by hariclerry

### What does this PR do?
This PR Makes translations of exercises and ingredients easier 

#### Description of Task to be completed?
The user should be able to select which languages to show. They should not be shown only their current language.

### How should this be manually tested?

1. Follow the setup instructions in [README.rst](https://github.com/andela/wg-rogue-one/blob/ft-translate-exercises-and-ingredients-157731616/README.rst)
2. Log in as an admin(Use default Username: admin, Password: admin)
3. From the dashboard, click on the exercise tab, select exercise overview link from the drop-down menu.
4. From the overview page, you show be able to see a select language option button, choose the language to view the list of exercises added for that particular language. 
5. Repeat the above steps for ingredients with using the ingredients overview link under the nutrition tab.

### Screen Shots

### Any background context you want to provide?
This feature was not available.

### What are the relevant pivotal tracker stories?
[#157731616](https://www.pivotaltracker.com/story/show/157731616)

2018-06-22 07:19 UTC, hariclerry commented
Hey guys, can you please review my PR and let me know what you think. Am still fixing a few issues though.

2018-06-22 07:34 UTC, peterwade153 commented
Clean work

2018-06-25 08:36 UTC, peterwade153 commented on wger/exercises/tests/test_exercise.py
> +        self.assertEqual(response.status_code, 405)
add new line

2018-06-25 09:00 UTC, tibetegya commented
I think the task is incomplete please use ready for complete tasks only

2018-06-27 04:11 UTC, King-Benx commented
Harriet, please maintain the pep8 standards by running autopep8 against your work

2018-06-27 04:11 UTC, King-Benx requested changes
Harriet, please maintain the pep8 standards by running autopep8 against your work

2018-06-27 06:40 UTC, hariclerry commented
@King-Benx, I did.

2018-06-28 12:57 UTC, merged