#157731611 Creates an exercise information read-only API endpoint
andela/wg-rogue-one pull request #7
Opened 2018-05-30 13:49 UTC by dondrzzy

### What does this PR do?
This commit creates a new read-only API endpoint that collects all the information
of an exercise such as muscles, category, language, license, category, equipment, status in one request.
Add a new exercise-readonly API endpoint to wger/urls.py.
Add an ExerciseReadOnlyViewSet class to wger/exercises/api/views.py and initialize
it as a ReadOnlyModelViewSet to enable only the GET parameter,
Add ExerciseReadOnlySerializer class to wger/exercises/api/serializers.py to convert
the data into JSON format.

#### Description of Task to be completed?
There should be a new read-only API endpoint that collects all the information of an exercise such as muscles, category, images, etc. This makes it easier for clients to get all the information since only a single request is needed to be done.

#### How should this be manually tested?
1: Start the application and go to `About this Software` button then select `Rest API` from the dropdown list.
2: Click `Browse the API` and select the link attached to`exercise-readonly` from JSON object.
3: You should have a read only API endpoint displaying all the exercise information.

#### Any background context you want to provide?
This feature was not available.

#### What are the relevant pivotal tracker stories?
#157731611

2018-05-30 16:39 UTC, hariclerry commented
Code looks neat and good so far. I have not seen any test cases for the feature, doesn't it require testing too?

2018-05-31 09:23 UTC, emugaya requested changes
Update your PR to show how the request is made and the expected response.

2018-05-31 12:54 UTC, dondrzzy commented
@hariclerry , I have added tests for the changes made.
@emugaya , i have updated the PR, showing the request to be made and the expected response

2018-06-01 17:07 UTC, emugaya approved these changes

2018-06-01 17:08 UTC, merged