#157731618 Allow comparison of members
andela/wg-rogue-one pull request #9
Opened 2018-06-04 08:34 UTC by tibetegya

### What does this PR do?
Allows comparison of members in case they are training together where by you have a graph where the data for (selected) members is shown .
#### Description of Task to be completed?
1. Run Autopep8 on code base
2. add local seetings import to settings.py 
#### How should this be manually tested?
1. Run the commands below
```
$ git clone https://github.com/andela/wg-rogue-one.git

$ git checkout ft-allow-comparison-157731618

```
follow the setup instructions in [README.rst](https://github.com/andela/wg-rogue-one/blob/ch-heroku-deployment-157842572/README.rst)
2. Run the app with `python manage.py runserver`
3. To run tests use `python manage.py test`

#### Any background context you want to provide?
When two users are training together it would be useful to see a comparison of some sorts. A possibility would be to have a graph where the data for (selected) members is shown or, less nicely, at least have different graphs under each other.
 
#### What are the relevant pivotal tracker stories?
#157731618

2018-06-05 06:53 UTC, emugaya requested changes
@tibetegya Your commit message says nothing about allowing comparison of members. The PR should have how I test the feature when logged in,  not when I have pulled your code.

2018-06-05 06:55 UTC, emugaya commented
I see only `autopep8` related changes. Where is the code for comparing users?

2018-06-06 09:05 UTC, tibetegya commented
@emugaya i first ran autopep8 commands before starting on the task but i have updated the pr instructions to show how to test it

2018-06-08 11:35 UTC, emugaya commented
@tibetegya Please add the charts to the PR.

2018-06-08 13:55 UTC, emugaya commented on wger/gym/templates/gym/partial_user_list.html
> +                    <!-- {% else %}
Remove commented code.

2018-06-11 07:34 UTC, emugaya approved these changes

2018-06-11 09:53 UTC, merged